import discord

COLORS: dict[str, discord.Color] = {
    "white": discord.Color.from_rgb(255, 255, 255),
    "brown": discord.Color.from_rgb(119, 56, 22),
    "game_timeout": discord.Color.darker_grey(),
    "game_draw": discord.Color.light_grey(),
}

EMOJIS: dict[str, str] = {
    "a": "🇦",
    "b": "🇧",
    "c": "🇨",
    "d": "🇩",
    "e": "🇪",
    "f": "🇫",
    "g": "🇬",
    "h": "🇭",
    "i": "🇮",
    "j": "🇯",
    "k": "🇰",
    "l": "🇱",
    "m": "🇲",
    "n": "🇳",
    "o": "🇴",
    "p": "🇵",
    "q": "🇶",
    "r": "🇷",
    "s": "🇸",
    "t": "🇹",
    "u": "🇺",
    "v": "🇻",
    "w": "🇼",
    "x": "🇽",
    "y": "🇾",
    "z": "🇿",
    "0": "0️⃣",
    "1": "1️⃣",
    "2": "2️⃣",
    "3": "3️⃣",
    "4": "4️⃣",
    "5": "5️⃣",
    "6": "6️⃣",
    "7": "7️⃣",
    "8": "8️⃣",
    "9": "9️⃣",
    "game_draw": "🤝",
    "game_win": "🏆",
    "game_loss": "🥀",
    "game_turn": "⏳",
    "game_timeout": "⏰",
    "game_surrender": "🏳️",
    "trivia_correct_answer": "✅",
    "trivia_wrong_answer": "❌",
    "trivia_correct_answer_selected": "✔️",
    "trivia_wrong_answer_selected": "✖️",
    "tic_empty_cell": "⬛",
    "wordle_enter_guess_button": "✏️",
    "wordle_random_guess_button": "🎲",
    "wordle_unused_letter": "⬜",
    "wordle_correct_letter": "🟩",
    "wordle_misplaced_letter": "🟨",
    "wordle_incorrect_letter": "⬛",
    "confirm_button": "✔️",
    "cancel_button": "✖️",
}
