"""add songless tables

Revision ID: 19b461c0ca7b
Revises: e230d678fc75
Create Date: 2026-08-22 21:45:03.841771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19b461c0ca7b'
down_revision: Union[str, Sequence[str], None] = 'e230d678fc75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ALL', 'POP', 'HIP_HIP', 'ROCK', name='esonglesscategory').create(op.get_bind())
    op.create_table('songless_song',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('category', postgresql.ENUM('ALL', 'POP', 'HIP_HIP', 'ROCK', name='esonglesscategory', create_type=False), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songless_match',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('song_id', sa.String(length=5), nullable=False),
    sa.Column('guesses_count', sa.Integer(), nullable=False),
    sa.Column('is_daily', sa.Boolean(), nullable=False),
    sa.Column('category', postgresql.ENUM('ALL', 'POP', 'HIP_HIP', 'ROCK', name='esonglesscategory', create_type=False), nullable=False),
    sa.Column('guesses', sa.ARRAY(sa.String(length=5)), nullable=False),
    sa.CheckConstraint('guesses_count BETWEEN 0 AND 6', name='valid_guesses'),
    sa.ForeignKeyConstraint(['match_id'], ['match.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songless_match')
    op.drop_table('songless_song')
    sa.Enum('ALL', 'POP', 'HIP_HIP', 'ROCK', name='esonglesscategory').drop(op.get_bind())
    # ### end Alembic commands ###
