"""initial_schema

Revision ID: 236201b498ae
Revises: 
Create Date: 2026-07-12 08:55:21.611322

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '236201b498ae'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('match_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'WIN', 'LOSS', 'TIMEOUT', 'DRAW', name='ematchstatus'), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('tic_tac_toe_match',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('opponent_id', sa.BigInteger(), nullable=False),
    sa.Column('total_moves', sa.Integer(), nullable=False),
    sa.Column('grid_size', sa.Integer(), nullable=False),
    sa.CheckConstraint('grid_size BETWEEN 3 AND 5', name='valid_grid_size'),
    sa.CheckConstraint('total_moves BETWEEN 0 AND grid_size * grid_size', name='valid_total_moves'),
    sa.ForeignKeyConstraint(['match_id'], ['match.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('wordle_match',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('secret_word', sa.String(length=5), nullable=False),
    sa.Column('guesses', sa.Integer(), nullable=False),
    sa.CheckConstraint('guesses BETWEEN 0 AND 6', name='valid_guesses'),
    sa.ForeignKeyConstraint(['match_id'], ['match.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wordle_match')
    op.drop_table('tic_tac_toe_match')
    op.drop_table('match')
    # ### end Alembic commands ###
