"""add command log

Revision ID: 313d12d2dd60
Revises: e86334c0f3c0
Create Date: 2026-08-14 21:07:15.089644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313d12d2dd60'
down_revision: Union[str, Sequence[str], None] = 'e86334c0f3c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('command_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_log_command_name'), 'command_log', ['command_name'], unique=False)
    op.create_index(op.f('ix_command_log_user_id'), 'command_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_command_log_user_id'), table_name='command_log')
    op.drop_index(op.f('ix_command_log_command_name'), table_name='command_log')
    op.drop_table('command_log')
    # ### end Alembic commands ###
