"""add log

Revision ID: 397b5437900e
Revises: 313d12d2dd60
Create Date: 2026-08-17 15:18:45.109660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397b5437900e'
down_revision: Union[str, Sequence[str], None] = '313d12d2dd60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_level'), 'log', ['level'], unique=False)
    op.create_index(op.f('ix_log_module'), 'log', ['module'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_module'), table_name='log')
    op.drop_index(op.f('ix_log_level'), table_name='log')
    op.drop_table('log')
    # ### end Alembic commands ###
