"""enable unaccent extension

Revision ID: 3a21ed11a39f
Revises: d82a01054d54
Create Date: 2026-09-02 19:03:48.916670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a21ed11a39f'
down_revision: Union[str, Sequence[str], None] = 'd82a01054d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS unaccent;")
    # ### end Alembic commands ###
