"""expand songless categories

Revision ID: 3c2e5d1df5e2
Revises: 3a21ed11a39f
Create Date: 2026-09-04 22:13:56.489295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '3c2e5d1df5e2'
down_revision: Union[str, Sequence[str], None] = '3a21ed11a39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='esonglesscategory',
        new_values=['ALL', 'HIP_HOP', 'ROCK', 'POP', 'CZECH_HITS', 'GAMING', 'CZSK_RAP'],
        affected_columns=[TableReference(table_schema='public', table_name='songless_match', column_name='category'), TableReference(table_schema='public', table_name='songless_song', column_name='category')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###

    # Migrate existing 'ALL' records to 'POP'
    op.execute("UPDATE songless_match SET category = 'POP' WHERE category = 'ALL';")
    op.execute("UPDATE songless_song SET category = 'POP' WHERE category = 'ALL';")


def downgrade() -> None:
    """Downgrade schema."""
    # Revert data from 'POP' and 'CZSK_RAP' back to 'ALL' BEFORE shrinking the enum
    # If this is not done, Postgres will throw an error when trying to remove in-use enum values.
    op.execute("UPDATE songless_match SET category = 'ALL' WHERE category IN ('POP', 'CZSK_RAP');")
    op.execute("UPDATE songless_song SET category = 'ALL' WHERE category IN ('POP', 'CZSK_RAP');")

    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='esonglesscategory',
        new_values=['ALL', 'HIP_HOP', 'ROCK', 'CZECH_HITS', 'GAMING'],
        affected_columns=[TableReference(table_schema='public', table_name='songless_match', column_name='category'), TableReference(table_schema='public', table_name='songless_song', column_name='category')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
