"""update songless categories

Revision ID: 44202cb55aa4
Revises: 19b461c0ca7b
Create Date: 2026-08-23 10:22:17.666974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '44202cb55aa4'
down_revision: Union[str, Sequence[str], None] = '19b461c0ca7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='esonglesscategory',
        new_values=['ALL', 'HIP_HOP', 'ROCK'],
        affected_columns=[TableReference(table_schema='public', table_name='songless_match', column_name='category'), TableReference(table_schema='public', table_name='songless_song', column_name='category')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='esonglesscategory',
        new_values=['ALL', 'POP', 'HIP_HIP', 'ROCK'],
        affected_columns=[TableReference(table_schema='public', table_name='songless_match', column_name='category'), TableReference(table_schema='public', table_name='songless_song', column_name='category')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
