"""update songless match guesses type

Revision ID: 89e41c7b51b3
Revises: 44202cb55aa4
Create Date: 2026-08-30 10:00:59.308950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89e41c7b51b3'
down_revision: Union[str, Sequence[str], None] = '44202cb55aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songless_match', 'guesses',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=5)),
               type_=sa.ARRAY(sa.BigInteger()),
               existing_nullable=False,
               postgresql_using="guesses::bigint[]") # Added explicit type cast
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songless_match', 'guesses',
               existing_type=sa.ARRAY(sa.BigInteger()),
               type_=postgresql.ARRAY(sa.VARCHAR(length=5)),
               existing_nullable=False,
               postgresql_using="guesses::varchar(5)[]") # Added explicit reverse cast
    # ### end Alembic commands ###
