"""add trivia models

Revision ID: 90371afcd6ff
Revises: 236201b498ae
Create Date: 2026-07-17 19:50:25.825348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90371afcd6ff'
down_revision: Union[str, Sequence[str], None] = '236201b498ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trivia_match',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('ANY', 'GENERAL_KNOWLEDGE', 'BOOKS', 'FILM', 'MUSIC', 'MUSICALS_AND_THEATERS', 'TELEVISION', 'VIDEO_GAMES', 'BOARD_GAMES', 'SCIENCE_AND_NATURE', 'COMPUTERS', 'MATHEMATICS', 'MYTHOLOGY', 'SPORTS', 'GEOGRAPHY', 'HISTORY', 'POLITICS', 'ART', 'CELEBRITIES', 'ANIMALS', 'VEHICLES', 'COMICS', 'GADGETS', 'ANIME_AND_MANGA', 'CARTOON_AND_ANIMATION', name='etriviacategory'), nullable=False),
    sa.Column('difficulty', sa.Enum('ANY', 'EASY', 'MEDIUM', 'HARD', name='etriviadifficulty'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trivia_match')
    # ### end Alembic commands ###
