"""add_surrender_match_status

Revision ID: a15b01a33d4e
Revises: 90371afcd6ff
Create Date: 2026-08-09 18:43:07.292388

"""
from collections.abc import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'a15b01a33d4e'
down_revision: str | Sequence[str] | None = '90371afcd6ff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='ematchstatus',
        new_values=['PENDING', 'WIN', 'LOSS', 'TIMEOUT', 'DRAW', 'SURRENDER'],
        affected_columns=[TableReference(table_schema='public', table_name='match', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='ematchstatus',
        new_values=['PENDING', 'WIN', 'LOSS', 'TIMEOUT', 'DRAW'],
        affected_columns=[TableReference(table_schema='public', table_name='match', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
