"""update songless match

Revision ID: d10a4d8b1da5
Revises: 44202cb55aa4
Create Date: 2026-08-30 12:03:55.935492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd10a4d8b1da5'
down_revision: Union[str, Sequence[str], None] = '44202cb55aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songless_match', 'song_id',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.BigInteger(),
               existing_nullable=False,
               postgresql_using="song_id::bigint",  # Added explicit type cast
    )
    op.alter_column('songless_match', 'guesses',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=5)),
               type_=sa.ARRAY(sa.BigInteger()),
               existing_nullable=False,
               postgresql_using="guesses::bigint[]",  # Added explicit type cast
    )
    op.create_foreign_key(None, 'songless_match', 'songless_song', ['song_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songless_match', type_='foreignkey')
    op.alter_column('songless_match', 'guesses',
               existing_type=sa.ARRAY(sa.BigInteger()),
               type_=postgresql.ARRAY(sa.VARCHAR(length=5)),
               existing_nullable=False,
               postgresql_using="guesses::varchar(5)[]",  # Added explicit reverse cast
    )
    op.alter_column('songless_match', 'song_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False,
               postgresql_using="song_id::varchar(5)",  # Added explicit reverse cast
    )
    # ### end Alembic commands ###
