"""rename match id attribute

Revision ID: d82a01054d54
Revises: 7016ca90133a
Create Date: 2026-09-01 22:01:06.359633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82a01054d54'
down_revision: Union[str, Sequence[str], None] = '7016ca90133a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'match_id', new_column_name='id')
    op.drop_constraint(op.f('songless_match_match_id_fkey'), 'songless_match', type_='foreignkey')
    op.create_foreign_key(None, 'songless_match', 'match', ['match_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tic_tac_toe_match_match_id_fkey'), 'tic_tac_toe_match', type_='foreignkey')
    op.create_foreign_key(None, 'tic_tac_toe_match', 'match', ['match_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('trivia_match_match_id_fkey'), 'trivia_match', type_='foreignkey')
    op.create_foreign_key(None, 'trivia_match', 'match', ['match_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('wordle_match_match_id_fkey'), 'wordle_match', type_='foreignkey')
    op.create_foreign_key(None, 'wordle_match', 'match', ['match_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wordle_match', type_='foreignkey')
    op.create_foreign_key(op.f('wordle_match_match_id_fkey'), 'wordle_match', 'match', ['match_id'], ['match_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'trivia_match', type_='foreignkey')
    op.create_foreign_key(op.f('trivia_match_match_id_fkey'), 'trivia_match', 'match', ['match_id'], ['match_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'tic_tac_toe_match', type_='foreignkey')
    op.create_foreign_key(op.f('tic_tac_toe_match_match_id_fkey'), 'tic_tac_toe_match', 'match', ['match_id'], ['match_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'songless_match', type_='foreignkey')
    op.create_foreign_key(op.f('songless_match_match_id_fkey'), 'songless_match', 'match', ['match_id'], ['match_id'], ondelete='CASCADE')
    op.alter_column('match', 'id', new_column_name='match_id')
    # ### end Alembic commands ###
