"""increase log message length

Revision ID: e230d678fc75
Revises: 397b5437900e
Create Date: 2026-08-17 19:17:10.192022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e230d678fc75'
down_revision: Union[str, Sequence[str], None] = '397b5437900e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'message',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=4096),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'message',
               existing_type=sa.String(length=4096),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###
