"""expand_wordle_match_columns

Revision ID: e86334c0f3c0
Revises: a15b01a33d4e
Create Date: 2026-08-09 20:35:13.639214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86334c0f3c0'
down_revision: Union[str, Sequence[str], None] = 'a15b01a33d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'wordle_match', 
        sa.Column('is_daily', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    op.alter_column('wordle_match', 'guesses', new_column_name='guesses_count')
    op.add_column(
        'wordle_match', 
        sa.Column('guesses', sa.ARRAY(sa.String(length=5)), nullable=False, server_default=sa.text("'{}'"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wordle_match', 'guesses')
    op.alter_column('wordle_match', 'guesses_count', new_column_name="guesses")
    op.drop_column('wordle_match', 'is_daily')